### ISSUE TITLE
Created a Telegram Bot using this

### ISSUE THREAD

**Issue by pachax001** [Prudhvi-pln/udb#10]
Here is the repo.
https://github.com/pachax001/My-Asian-Tv-Dramacool-Telegram-bot
 I need to know is how the download progress is calculated?

**Comment by Prudhvi-pln** [comment]
Hi @pachax001, thanks for using UDB 🙂. Good to see it implemented in your project👍.

Downloads happen in 2 ways:
1. Streaming (HLS) - most common (95%)
2. MP4

- In case of Streaming, the video comes in multiple parts (called as segments). The download progress is tracked as segments downloaded / total no. of segments. _Note: It is possible to track download progress in terms of file size (MB), but that would consume a lot of network bandwidth and slows down the downloads_
- In case of MP4, the download progress is measured as data downloaded / total file size.
- As for the progress, I'm using [tqdm](https://pypi.org/project/tqdm/) module to display download progress.

Feel free to comment back if you have any other questions. Also, do add any feature requests if you feel can be implemented.
Let's make UDB the go-to downloader for Anime & Drama fans!

**Comment by Prudhvi-pln** [comment]
@pachax001, please close this issue, if your query is answered.
