### ISSUE TITLE
Support for English movies and tv shows maybe??

### ISSUE THREAD

**Issue by francqz31** [Prudhvi-pln/udb#11]
Hey amazing repo , I use it a lot and like it.
is it possible that you might add support for English movies and Tv shows  from https://hurawatch.bz/home or https://fmoviesz.to/home for example.

Thanks in advance.

**Comment by Prudhvi-pln** [comment]
Hi, thanks for using UDB. I do want to extend the support to TV shows, but I could not find a stable website. Unfortunately, even the ones you provided are not opening for me :(

If I could find a good stable website, I will definitely add the support.

**Comment by Prudhvi-pln** [comment]
Wow.. great. That's a lot 😅. Let me try them in my browser also via API.

**Comment by Prudhvi-pln** [comment]
Hi, Sorry I couldn't find time to do this. I actually looked into this and found it to be more complicated. Technically speaking, it has many layers of decryption using javascripts. And many thanks for the repo, it helps me to proceed further in my research. I'm trying to create a working code by this weekend. Please look forward to it. Thanks!

**Comment by Prudhvi-pln** [comment]
@francqz31, hope you are doing good! All new UDB v2.12.0 is here with support for Movies, TV Shows.
Please update your UDB: `python udb.py -u`.
Let me know your feedback after using it. Thanks!

**Comment by Prudhvi-pln** [comment]
Hope this request is finished. I am closing this. If you face any issues, please feel free to raise a new issue.
Thank you for your support to add this feature. Happy Binge Watching 😄 !!!
