### ISSUE TITLE
AnimePahe Issue

### ISSUE THREAD

**Issue by activ33** [Prudhvi-pln/udb#12]
Hello ! 
When ever I try to download Anime Using AnimePahe from your repo using Termux It shows this

Search Results:
AnimePahe requires a chrome browser to be installed. Unable to proceed further!

**Comment by Prudhvi-pln** [comment]
Hi, thanks for using UDB. Unfortunately, current version does not support Animepahe on Termux as it is not a standalone linux distro.
I'll try looking for an alternative and let you know.

Meanwhile, please feel free to use the other anime client (GogoAnime).

**Comment by activ33** [comment]
Ok, thankyou for your repo.

**Comment by Prudhvi-pln** [comment]
Default termux cannot support Chromedriver, so AnimePahe can't work. There are a couple of solutions:

1. Using proot & adb -- has security concerns, so not recommended
2. Install Ubuntu or any Linux distro -- requires more disk space

Closing this issue, as it is a platform limitation. Please use GogoAnime Client and do let me know if there are any concerns.

Thank you!
