### ISSUE TITLE
Nestled Episodes

### ISSUE THREAD

**Issue by ZetsApocNow** [Prudhvi-pln/udb#13]
Downloading English TV Series seems to nestle each episode inside it's own folder

![image](https://github.com/Prudhvi-pln/udb/assets/93975191/6d74de90-862e-40d2-95a9-811d5f9fd09a)

**Comment by ZetsApocNow** [comment]
also for some reason Movies and TV Shows isn't finding download links anymore, the other options work though

**Comment by Prudhvi-pln** [comment]
Hi @ZetsApocNow, thank you for using UDB. 

Regarding the first issue, I tried downloading the same series, and it worked fine for me:
![image](https://github.com/Prudhvi-pln/udb/assets/62585477/772cc1da-ad42-490b-ab86-5f1e008a64ef)

And for second issue, can you please be more specific, also can you attach any screenshots / logs to help debug it. Because I am able to download.

**Comment by ZetsApocNow** [comment]
I think it was time based, didn't work for 4-5 hours in the evening but now is finding download links. Included my log file.

[udb.log](https://github.com/Prudhvi-pln/udb/files/15023357/udb.log)

Just downloaded W13 again, same nestled folders, when the entire season is downloaded, not just 1 episode. Also downloaded a fresh copy of the git onto another drive and ran it, same issue, happens with any series found by the 4th option.

![Animation156](https://github.com/Prudhvi-pln/udb/assets/93975191/76cc68a0-4c70-463f-b8a4-bb9dfd3892f0)

**Comment by Prudhvi-pln** [comment]
Thanks for the detailed inputs.

I fixed the nesting issue:
![image](https://github.com/Prudhvi-pln/udb/assets/62585477/adf73e07-fb81-4b39-a20e-5e0fe7316e14)

And the multi seasons download issue:
![image](https://github.com/Prudhvi-pln/udb/assets/62585477/7356d9bb-909b-496e-a51c-db22eb428918)

Also, made it more readable in case of multiple seasons.

Please update your UDB and let me know if the issue still exists.

But, I could not simulate the 3rd issue @francqz31 mentioned. Can you please provide more info like series name, season & episode number where you faced this issue.

**Comment by Prudhvi-pln** [comment]
@ZetsApocNow, regarding download links not loading, it looks like it is a network issue. The source website (vidsrc.to) is sometimes blocked in few networks. I faced a similar issue with a different network :(

I am looking into a few alternatives and will get back with a solution. An immediate solution would be setting up a proxy or changing your network.

**Comment by ZetsApocNow** [comment]
@Prudhvi-pln yeah that fixed it thanks

**Comment by Prudhvi-pln** [comment]
> Ok so I did extensive research , and revisited most of the streaming websites again , and looked at the episodes that had `Resolution {} not found` , and I found that there is a better host server than vidplay aka "vidsrc.to and vidsrc.me" and it is called "Upcloud" , this server mostly doesn't break the way vidsrc does and does have more episodes than vidsrc on the usual. I haven't found a scraper for it yet , but i found this https://github.com/UpCloudLtd/upcloud-python-api so idk should we have an option to choose between hosts maybe , or should we just stick to vidsrc and its errors.

@francqz31, yes, it is a vidsrc issue. I noticed it too. I'm researching a few other servers, but they follow their own algorithm. So, I'll need some time to analyze. Meanwhile please feel free to drop any leads, if you have.

I'm tracking this as a separate issue #15 . Closing this issue.
