### ISSUE TITLE
Error 404 page

### ISSUE THREAD

**Issue by pachax001** [Prudhvi-pln/udb#18]
As you see in myasiatv there are removed pages like https://myasiantv.ac/kshow/eden
Do asearch eden in myasiantv and you in the first result of search you get a removed show.
When this happen I get error
Search Results:
Failed with code: 404
Error occurred: 'NoneType' object has no attribute 'select'. Check log for more details.

**Comment by Prudhvi-pln** [comment]
Fixed in v2.12.4
