### ISSUE TITLE
Vidplay source id not found in sources

### ISSUE THREAD

**Issue by ZetsApocNow** [Prudhvi-pln/udb#20]
![image](https://github.com/Prudhvi-pln/udb/assets/93975191/3abe905b-1e4e-4fd9-b79d-7751996af787)

"Vidplay source id not found in sources"

Getting this suddenly on everything

**Comment by Prudhvi-pln** [comment]
Thanks for noticing it. There is change in Vidplay source identifier. Fixed this in v2.12.5.
Please re-open if issue still exists.

**Comment by ZetsApocNow** [comment]
Fix worked for a bit, now just says No download links found. on everything, waited a couple of days, still happening.

**Comment by Prudhvi-pln** [comment]
The backend source [vidsrc] requires extra keys. From last few days, they are changing the keys frequently, this is breaking down the system. 
I am working on 2 things: 1. a new client & 2. more reliable keys extractor. Let's see which will be completed first 🙂.

**Comment by Prudhvi-pln** [comment]
@ZetsApocNow, All new UDB v2.13.0 is here with faster vidsrc keys refresh (but not 100% 😅) and new Superembed client (alternate to Vidsrc and better catalog).

For vidsrc, I will try to keep the keys updated till I find a standalone solution.
