### ISSUE TITLE
Vidsrc and Superembed can't download

### ISSUE THREAD

**Issue by ChaoFansxcz** [Prudhvi-pln/udb#24]
![Screenshot_2024-09-19-10-27-02-432_com termux](https://github.com/user-attachments/assets/c195a8eb-bfcb-4615-afe6-d8528bfcbf44)
![Screenshot_2024-09-19-10-28-00-271_com termux](https://github.com/user-attachments/assets/151c90bc-94f8-4911-b5fa-ce7f4bcb7632)
Hello sir, can't download any movie or drama via vidsrc and superembed

**Comment by Prudhvi-pln** [comment]
Hi @ChaoFansxcz, unfortunately, vidsrc is down and I am not able to find a stable alternate yet. For superembed, you'll need a chrome browser for initial load (which is not available on Termux natively). 

An alternate is to load the cookies created from a PC / laptop.

PS: Feel free to address me using a mention, without 'sir' 🙂

**Comment by Prudhvi-pln** [comment]
If you do not have a PC available, do the following:
1. Navigate to udb installation directory in your mobile
2. Navigate to `Clients` folder
3. Create a file with name `.udb_client_cookies.json` with below content:
    ```
    {"superembed": {"button-click": "ZEhKMVpTLVF0LVBTLVF0Ty0wVXpMUy1RMS1QalV0TC0wLVYzLVAtMGsyTmpjLVFOemN6LVBELVAtNQ=="}}
    ```
4. Reload udb session.

**Comment by Prudhvi-pln** [comment]
@ChaoFansxcz, did the above steps work for you ??

**Comment by Prudhvi-pln** [comment]
Hope the above solution worked for you. Closing this issue, as there is no further update. Please reopen in case issue still exists.

**Comment by dd900** [comment]
I just tried this and it did not work for me

**Comment by Prudhvi-pln** [comment]
@dd900, this is something new. Looks like superembed itself is not working:
![image](https://github.com/user-attachments/assets/b0c6e22f-c3ce-4f8a-bcdb-10633b32938c)

I guess superembed is also dead now. 😞
