### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by pachax001** [Prudhvi-pln/udb#3]
Some dramas doesn't have all the qualities. 
Assume a drama has 16 episodes.
Some episodes are only in 480p and some are in 360p
So user choose 480p. This will only download 480p but not 360p.
So improve the script to download the next low quality video (in here 360p)
So if user select 720p and cannot find 720p video then it will download the next available low quality video

**Comment by Prudhvi-pln** [comment]
@pachax001, Thanks for the suggestion. I've added it as a feature. Please do a fresh pull from the main branch, and let me know if you face any issues.
