### ISSUE TITLE
there is ddos guard in animepahe website

### ISSUE THREAD

**Issue by Badaryman** [Prudhvi-pln/udb#7]
Please Update

**Comment by Prudhvi-pln** [comment]
Thanks for pointing it out. I've observed this and working on a fix to bypass DDoS check. Will provide a fix at the earliest.

**Comment by Badaryman** [comment]
Traceback (most recent call last):
  File "C:\Users\Guzman\Downloads\Programs\udb\udb.py", line 9, in <module>
    from Clients.AnimeClient import AnimeClient
  File "C:\Users\Guzman\Downloads\Programs\udb\Clients\AnimeClient.py", line 8, in <module>
    from Clients.BaseClient import BaseClient
  File "C:\Users\Guzman\Downloads\Programs\udb\Clients\BaseClient.py", line 14, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by Badaryman** [comment]
@Prudhvi-pln

**Comment by Prudhvi-pln** [comment]
@Badaryman, This is an existing dependency only. Please install dependencies via requirements.txt, and let me know if the issue still exists.

**Comment by Badaryman** [comment]
i tried this
pip install pycryptodomex

and changing the base client to this
from Cryptodome.Cipher import AES

works now

**Comment by Badaryman** [comment]
![image](https://github.com/Prudhvi-pln/udb/assets/154390732/538fa62c-1c2c-43c9-9d92-3c44901ab2ed)
btw new version works now thanks
