### ISSUE TITLE
Add support for GogoAnime

### ISSUE THREAD

**Issue by Prudhvi-pln** [Prudhvi-pln/udb#8]
Currently, Animepahe is the source for anime. But updates for a new episode are a bit slower compared to Gogoanime (occasionally). So, planning to add support for GogoAnime. Note: Support for animepahe should still continue, and user should have the option to select either of them.

**Comment by Prudhvi-pln** [comment]
Added support for GogoAnime in v2.11.0.

**Comment by Prudhvi-pln** [comment]
@Badaryman Pleasure is mine. Please feel free to add a feature request if you feel anything can be improved/added.

**Comment by Badaryman** [comment]
btw @Prudhvi-pln is it like possible to make a app/gui version of this, for me so it doesnt always run the py file like for the convenience of it

**Comment by Prudhvi-pln** [comment]
@Badaryman, Thanks for your input. I'm more of a CLI person😅. So, there are no immediate plans as of now, however, I'll note it into my backlog. Meanwhile, I just pushed a new version of UDB (v2.11.2) which is more visually pleasing. Please try it.

**Comment by Badaryman** [comment]
@Prudhvi-pln tried it now, good update btw thanks for the update
![image](https://github.com/Prudhvi-pln/udb/assets/154390732/2b207d1d-1f87-405e-a37b-c2bbc0f5ed2b)

**Comment by Badaryman** [comment]
@Prudhvi-pln can you also add anix.to as provider if possible?

**Comment by Prudhvi-pln** [comment]
@Badaryman can you help me understand why anix ? I don't see much difference compared to Gogoanime.
